twfy_mp:
  where: '/twfy/mp/:post_code'
  internal: true
  service_provider: 'they_work_for_you'
  name: 'Your MP'

broadband:
  where: '/broadband/:post_code'
  internal: true
  service_provider: 'broadband_summary'
  name: 'Broadband Availability'

council:
  where: '/council/:post_code'
  internal: true
  service_provider: 'council'
  name: 'Council'
